### ISSUE TITLE
Blockstack Update Required

### ISSUE THREAD

**Issue by cryptocracy** [cryptocracy/remark#1]
currently running 18.3.0 on the blockstack js for the app build.
But we need to get ready for ^19.0.0

We still need to make sure we update our source code to account for the deprecation that will be happening on the subsequent major release:

The static `isUserSignedIn()` function will be deprecated in the next major release of blockstack.js. Create an instance of `UserSession` and call the instance method `isUserSignedIn()`.

The static `getFile()` function will be deprecated in the next major release of blockstack.js. Create an instance of `UserSession` and call the instance method `getFile()`.

The static `loadUserData()` function will be deprecated in the next major release of blockstack.js. Create an instance of `UserSession` and call the instance method `loadUserData()`.

**Comment by akashkaushik33** [comment]
Blockstack version upgraded and created a pull request to master.  https://github.com/cryptocracy/remark/pull/13

**Comment by cryptocracy** [comment]
@akashkaushik33 rocks !
