### ISSUE TITLE
Feature Request: Footer Player

### ISSUE THREAD

**Issue by cryptocracy** [cryptocracy/remark#2]
We need to 
- [x] add a persistent footer player to enable playback of audio while navigating around the app.
- [x] up the playback to a temp array that represents the current list of audio to playback. (the active playlist). 
- [x] autoplay the active playlist.

Note: This will allow for extending of component to take in custom playlists for playback.

**Comment by akashkaushik33** [comment]
Just created a PR for the same https://github.com/cryptocracy/remark/pull/7#issue-272238613
