### ISSUE TITLE
Feature Request: Customized Channels

### ISSUE THREAD

**Issue by cryptocracy** [cryptocracy/remark#3]
Each channel owner needs to have the ability to set 2 additional custom properties:
- [x] add a custom header Image for their channel.
- [x] add a custom short description to the channel.
- [x] add a list of the channels associated `my_sounds.json` under the row of buttons

Note: Play now and add to playlist should work just like the other audio listings (reference SoundInfo.vue or Quorum.vue)

**Comment by cryptocracy** [comment]
@akashkaushik33 ... Now that we've got the blockstack version upgrade sorted out, can you please take a look at @alexiinnn `customized_channels` branch and see what we can do to get the 3 items in this issue knocked out.

**Comment by akashkaushik33** [comment]
I did not understand the 3rd point "add a list of the channels associated my_sounds.json under the row of buttons", please give some more info on this.

**Comment by akashkaushik33** [comment]
Pushed the code in feat/issue3 branch yesterday.
Please take a look.
